export type AttendanceStatus =
  | 'presente'
  | 'falta_injustificada'
  | 'falta_justificada'
  | 'atestado_medico'
  | 'atraso';

export type UserRole = 'admin' | 'gestao_paac' | 'aoe' | 'professor';

export interface UserAccount {
  id: string;
  name: string;
  username: string;
  role: UserRole;
  roleLabel: string;
  pin: string; // Senha numérica de 4 dígitos (ex: "1234")
  createdAt: string;
  lastLogin?: string;
  active: boolean;
  notes?: string;
}

export interface UserSession {
  id?: string;
  username: string;
  name: string;
  role: UserRole;
  roleLabel: string;
}

export type GateMovementType = 'entrada_tardia' | 'saida_antecipada';

export interface GateRecord {
  id: string;
  studentId: string;
  studentName: string;
  classId: string;
  className: string;
  date: string; // YYYY-MM-DD
  time: string; // HH:MM
  type: GateMovementType;
  reason: string;
  guardianOrAuthorizedPerson: string;
  guardianPhone?: string;
  recordedBy: string;
  notes?: string;
}
export type RiskLevel = 'baixo' | 'moderado' | 'alto' | 'critico';
export type StudentStatus = 'regular' | 'alerta' | 'evasao_iminente' | 'em_busca_ativa' | 'reintegrado';

export interface Student {
  id: string;
  name: string;
  ra: string; // Registro do Aluno
  classId: string;
  className: string;
  guardianName: string;
  guardianPhone: string;
  guardianRelationship: string;
  address: string;
  neighborhood: string;
  status: StudentStatus;
  riskLevel: RiskLevel;
  totalSchoolDays: number;
  totalAbsences: number;
  consecutiveAbsences: number;
  attendanceRate: number; // 0 - 100%
  vulnerabilityFactors: string[];
  lastAttendanceDate: string;
  activeInterventionId?: string;
  notes?: string;
}

export interface AttendanceRecord {
  id: string;
  studentId: string;
  studentName: string;
  classId: string;
  className?: string;
  date: string; // YYYY-MM-DD
  status: AttendanceStatus;
  durationDays?: number; // Duração em dias (1, 2, 3...) quando a falta/justificativa for superior a 1 dia
  justification?: string;
  medicalCertificate?: string; // Informações do atestado médico (dias e motivo)
  medicalDays?: number; // Quantidade de dias do atestado
  isCountedAsAbsence?: boolean; // false para atestado médico (não contabiliza ausência), true para falta justificada/injustificada
  recordedBy: string;
  recordedAt?: string;
  createdAt?: string;
}

export type AlertChannel = 'whatsapp' | 'sms' | 'ligacao' | 'notificacao_push';
export type AlertTrigger =
  | '1_falta'
  | '2_faltas_consecutivas'
  | '3_faltas_consecutivas'
  | 'mais_de_3_conselho_tutelar'
  | 'dias_alternados_baixa_frequencia'
  | '5_faltas_mes'
  | 'frequencia_abaixo_75'
  | 'falta_reincidente_sexta_segunda'
  | 'alerta_manual';

export type AlertStatus = 'enviado' | 'entregue' | 'lido' | 'respondido' | 'falha';

export interface ParentAlert {
  id: string;
  studentId: string;
  studentName: string;
  classId: string;
  className: string;
  guardianName: string;
  guardianPhone: string;
  channel: AlertChannel;
  triggerReason: AlertTrigger;
  triggerLabel: string;
  messageContent: string;
  status: AlertStatus;
  sentAt: string;
  readAt?: string;
  guardianFeedback?: string;
  autoGenerated: boolean;
}

export type InterventionStage =
  | 'alerta_inicial'
  | 'contato_telefonico_whatsapp'
  | 'reuniao_pais'
  | 'encaminhado_cras_conselho'
  | 'reintegrado'
  | 'encerrado';

export interface InterventionActionLog {
  id: string;
  date: string;
  action: string;
  author: string;
  notes: string;
  result: string;
}

export interface InterventionCase {
  id: string;
  studentId: string;
  studentName: string;
  classId: string;
  className: string;
  guardianName: string;
  guardianPhone: string;
  priority: 'media' | 'alta' | 'urgente_conselho';
  stage: InterventionStage;
  openedAt: string;
  lastUpdatedAt: string;
  assignedPedagogue: string;
  reason: string;
  actionLog: InterventionActionLog[];
  actionPlan: string[];
  targetReturnDate?: string;
  resolvedDate?: string;
}

export interface SchoolClass {
  id: string;
  name: string;
  grade: string;
  shift: 'Manhã' | 'Tarde' | 'Integral' | 'Noite';
  totalStudents: number;
  presentToday: number;
  absentToday: number;
  attendanceRateToday: number;
  studentsAtRiskCount: number;
}

export interface MonthlyPedagogicalReport {
  month: string;
  monthIndex: number; // 1-12
  year: number;
  totalEnrolled: number;
  averageAttendanceRate: number;
  totalAbsences: number;
  studentsWithCriticalAbsence: number; // < 75%
  activeSearchCasesCount: number;
  successfulReintegrations: number;
  alertsDispatched: number;
  alertsResponded: number;
  absenceCausesDistribution: { cause: string; count: number; percentage: number }[];
  riskByClass: { classId: string; className: string; averageAttendance: number; riskStudents: number; totalStudents: number }[];
  attendanceTrend: { week: string; rate: number; absences: number }[];
  pedagogicalInsights: string[];
}

export interface SeducContingencyReport {
  schoolName: string;
  officialHeader: string;
  subHeader: string;
  reportTitle: string;
  date: string;
  formattedDate: string;
  summary: {
    totalStudents: number;
    totalPresent: number;
    totalFaltaJustificada: number;
    totalFaltaInjustificada: number;
    totalAtestados: number;
    totalAtrasos: number;
    overallAttendanceRate: number;
  };
  classReports: {
    classId: string;
    className: string;
    shift: string;
    grade: string;
    totalEnrolled: number;
    presentCount: number;
    faltaJustificadaCount: number;
    faltaInjustificadaCount: number;
    atestadoMedicoCount: number;
    atrasoCount: number;
    attendanceRate: number;
    absentStudents: {
      id: string;
      name: string;
      ra: string;
      status: AttendanceStatus;
      isAbsent: boolean;
      isCountedAsAbsence: boolean;
      justification: string;
      medicalCertificate: string;
      consecutiveAbsences: number;
      totalAbsences: number;
      attendanceRate: number;
      guardianName: string;
      guardianPhone: string;
      gateRecord: { type: GateMovementType; time: string; reason: string } | null;
    }[];
  }[];
}

export interface GoogleSheetsConfig {
  spreadsheetId: string | null;
  spreadsheetUrl: string | null;
  title: string | null;
  lastSync: string | null;
  connectedUserEmail?: string | null;
  syncedCounts?: {
    students: number;
    attendance: number;
    interventions: number;
    gateRecords: number;
    alerts: number;
  };
}
